---
- name: Ansible Script for running multiple runners
  hosts: all
  become: true

  vars:
    runners:
      - runner1
      - runner2
      - runner3

  tasks:
    - name: Install python requests
      ansible.builtin.shell: pip3.13 install requests
      args:
        creates: /usr/local/lib/python3.13/site-packages/requests

    - name: Download Docker repo
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/rhel/docker-ce.repo
        dest: /etc/yum.repos.d/docker.repo
        mode: "0644"

    - name: Install Docker
      ansible.builtin.dnf:
        name: docker-ce
        state: present

    - name: Start Docker
      ansible.builtin.systemd_service:
        name: docker
        state: started
        enabled: true
        daemon-reload: true

    - name: Wait for docker socket
      ansible.builtin.wait_for:
        path: /var/run/docker.sock
        timeout: 60

    - name: Add github runner user
      ansible.builtin.user:
        name: github-runner
        home: /github-runner
        groups: docker
        append: true

    # Pull ONCE (no loop)
    - name: Pull runner image once
      community.docker.docker_image:
        name: chanu66/github-runner
        tag: latest
        source: pull

    # Run 3 containers (no pulling here)
    - name: Start runner containers
      community.docker.docker_container:
        name: "{{ item }}"
        image: chanu66/github-runner:latest
        state: started
        recreate: false
        restart_policy: always
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        env:
          NAME: "{{ item }}"
          TOKEN: "{{ TOKEN }}"
          ORG: "https://github.com/chanu-devops"
      loop: "{{ runners }}"